# game = KubaGame(('PlayerA', 'W'), ('PlayerB', 'B'))
# print("Board start (below)")
# game.display_board()
#
# print(game.get_marble((0, 0)))
#
#
# print("1 (below)", game.make_move('PlayerB', (0, 5), 'B'))
# game.display_board()
# print("2 (below)", game.make_move('PlayerA', (0, 1), 'B'))
# game.display_board()
# print("3 (below)", game.make_move('PlayerB', (1, 5), 'B'))
# game.display_board()
# print("4 (below)", game.make_move('PlayerA', (2, 1), 'R'))
# game.display_board()
# # print(game.get_current_turn())
# print("5 (below)", game.make_move('PlayerB', (3, 5), 'L'))
# game.display_board()
# print("6 (below)", game.make_move('PlayerA', (0, 0), 'B'))
# game.display_board()
# print("7 (below)", game.make_move('PlayerB', (2, 6), 'L'))
# game.display_board()
# print("8 (below)", game.make_move('PlayerA', (2, 0), 'R'))
# game.display_board()
# print("9 (below)", game.make_move('PlayerB', (2, 6), 'L'))
# game.display_board()
#
#
# # Display status of game:
# print('Current turn: ', game.get_current_turn())
# print('Marble count (W, B, R):', game.get_marble_count())
# print('PlayerA captured reds:', game.get_player('PlayerA').get_captured())
# print('PlayerB captured reds:', game.get_player('PlayerB').get_captured())
# print('Winner: ', game.get_winner())

# print("7 (below)", game.make_move('PlayerB', (3, 4), 'L'))
# game.display_board()
# print("9 (below)", game.make_move('PlayerA', (2, 3), 'R'))
# game.display_board()
# print("10 (below)", game.make_move('PlayerB', (3, 3), 'L'))
# game.display_board()
# print("11 (below)", game.make_move('PlayerA', (2, 4), 'R'))
# game.display_board()
# print("12 (below)", game.make_move('PlayerB', (3, 2), 'L'))
# game.display_board()
# print("13 (below)", game.make_move('PlayerA', (2, 5), 'R'))
# game.display_board()
# print("14 (below)", game.make_move('PlayerB', (3, 1), 'L'))
# game.display_board()
# print("15 (below)", game.make_move('PlayerA', (2, 6), 'F'))
# game.display_board()
# print("16 (below)", game.make_move('PlayerB', (6, 1), 'F'))
# game.display_board()
# print("17 (below)", game.make_move('PlayerA', (1, 6), 'F'))
# game.display_board()
# print("18 (below)", game.make_move('PlayerB', (4, 1), 'R'))
# game.display_board()
# print("19 (below)", game.make_move('PlayerA', (0, 6), 'B'))
# game.display_board()
# print("20 (below)", game.make_move('PlayerB', (4, 2), 'R'))
# game.display_board()
# print("21 (below)", game.make_move('PlayerA', (1, 0), 'R'))
# game.display_board()
# print("22 (below)", game.make_move('PlayerB', (4, 3), 'R'))
# game.display_board()
# print("23 (below)", game.make_move('PlayerA', (5, 6), 'L'))
# game.display_board()
# print("24 (below)", game.make_move('PlayerB', (4, 4), 'R'))
# game.display_board()
# print("23 (below)", game.make_move('PlayerA', (5, 6), 'L'))
# game.display_board()


# print("2", game.make_move('PlayerA', (2, 6), 'x'))
# print("3", game.make_move('PlayerA', (0, 6), 'F'))
# print("4", game.make_move('PlayerB', (0, 6), 'B'))
# print("5", game.make_move('PlayerB', (2, 6), 'L'))
# print("6", game.make_move('PlayerA', (0, 5), 'L'))
#
# game.display_board()
# print(game.get_marble_count())
# print("7", game.make_move('PlayerA', (6, 0), 'L'))
# print("8", game.make_move('PlayerB', (6, 6), 'R'))
# print("9", game.make_move('PlayerA', (6, 1), 'B'))
#
# game.display_board()
# print(game.get_marble_count())
